APP_DB_USERNAME: 'postgres'
APP_DB_PASSWORD: ''
APP_DB_NAME: 'postgres'
APP_DB_HOST: 'localhost'

TEST_DB_USERNAME: 'postgres'
TEST_DB_PASSWORD: ''
TEST_DB_NAME: 'sermo_test'
TEST_DB_HOST: 'localhost'

PORT: '8010'
SDP_PORT: 8080

SIGNING_KEY: 'sermoapisigningkey'
