APP_DB_USERNAME: 'postgres'
APP_DB_PASSWORD: ''
APP_DB_NAME: 'postgres'
APP_DB_HOST: 'localhost'

TEST_DB_USERNAME: 'postgres'
TEST_DB_PASSWORD: ''
TEST_DB_NAME: 'postgres'
TEST_DB_HOST: 'localhost'

PORT: '8010'
